from __future__ import annotations

import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass


class LearningSafetyViolation(ValueError):
    """Raised without retaining or echoing the rejected learning content."""

    def __init__(self, codes: tuple[str, ...]) -> None:
        self.codes = codes
        super().__init__("LEARNING_SAFETY_BLOCKED:" + ",".join(codes))


@dataclass(frozen=True)
class LearningSafetyResult:
    safe: bool
    violation_codes: tuple[str, ...]


# Evidence references are deliberately content-free. The digest is generated by
# the evidence store; URLs, file paths, labels, and source excerpts do not belong
# in learning records.
OPAQUE_EVIDENCE_REF_PATTERN = re.compile(r"\Aevidence://sha256/[0-9a-f]{64}\Z")

_SECRET_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "SECRET_PRIVATE_KEY",
        re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----", re.IGNORECASE),
    ),
    (
        "SECRET_API_KEY",
        re.compile(
            r"(?i)\b(?:api[_ -]?key|access[_ -]?key|client[_ -]?secret)\b"
            r"\s*(?:=|:)\s*['\"]?[A-Za-z0-9_./+=-]{12,}"
        ),
    ),
    (
        "SECRET_TOKEN",
        re.compile(
            r"(?i)(?:\b(?:bearer|token)\b\s*(?:=|:)?\s*['\"]?"
            r"[A-Za-z0-9_./+=-]{16,}|\b(?:gh[opsu]_[A-Za-z0-9]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}))"
        ),
    ),
    (
        "SECRET_PASSWORD",
        re.compile(
            r"(?i)\b(?:password|passwd|pwd)\b\s*(?:=|:)\s*['\"]?[^\s'\"]{8,}"
        ),
    ),
)

_EMAIL_PATTERN = re.compile(
    r"(?i)(?<![A-Z0-9.!#$%&'*+/=?^_`{|}~-])"
    r"[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?"
    r"(?:\.[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+(?![A-Z0-9-])"
)
_KOREAN_PHONE_PATTERN = re.compile(r"(?<!\d)01[016789][ -.]{0,1}\d{3,4}[ -.]{0,1}\d{4}(?!\d)")
_KOREAN_RRN_PATTERN = re.compile(r"(?<!\d)(\d{6})[- ]?([1-8]\d{6})(?!\d)")


def _has_valid_korean_rrn(text: str) -> bool:
    for match in _KOREAN_RRN_PATTERN.finditer(text):
        digits = tuple(int(value) for value in "".join(match.groups()))
        weighted = sum(
            value * weight
            for value, weight in zip(digits[:12], (2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5), strict=True)
        )
        if (11 - weighted % 11) % 10 == digits[12]:
            return True
    return False


def scan_learning_text(text: str) -> tuple[str, ...]:
    """Return stable violation codes only; never return or retain matched values."""

    codes = [code for code, pattern in _SECRET_PATTERNS if pattern.search(text)]
    if _has_valid_korean_rrn(text):
        codes.append("PII_KOREAN_RRN")
    if _KOREAN_PHONE_PATTERN.search(text):
        codes.append("PII_KOREAN_PHONE")
    if _EMAIL_PATTERN.search(text):
        codes.append("PII_EMAIL")
    return tuple(codes)


def scan_learning_payload(
    text_fields: Mapping[str, str | None],
    evidence_refs: Iterable[str],
) -> LearningSafetyResult:
    """Fail closed over candidate/lesson text and content-free evidence IDs."""

    codes: set[str] = set()
    try:
        values = tuple(text_fields.values())
        refs = tuple(evidence_refs)
    except (AttributeError, TypeError):
        return LearningSafetyResult(False, ("LEARNING_PAYLOAD_INVALID",))

    for value in values:
        if value is None:
            continue
        if not isinstance(value, str):
            codes.add("LEARNING_PAYLOAD_INVALID")
            continue
        codes.update(scan_learning_text(value))

    for ref in refs:
        if not isinstance(ref, str) or OPAQUE_EVIDENCE_REF_PATTERN.fullmatch(ref) is None:
            codes.add("EVIDENCE_REF_NOT_OPAQUE")
            continue
        # A canonical opaque digest contains no source content. Scanning its
        # hexadecimal payload as natural language creates phone/RRN false positives.

    ordered = tuple(sorted(codes))
    return LearningSafetyResult(not ordered, ordered)


def require_safe_learning_payload(
    text_fields: Mapping[str, str | None],
    evidence_refs: Iterable[str],
) -> None:
    result = scan_learning_payload(text_fields, evidence_refs)
    if not result.safe:
        raise LearningSafetyViolation(result.violation_codes)
