const effects=__PAYLOAD__, template=__TEMPLATE__, fonts=__FONTS__, get=id=>document.getElementById(id);
let output='', uploadedFont='';
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o);}
effects.forEach(e=>option(get('effect'),e.id,e.name));Object.entries(fonts).forEach(([id,[name]])=>option(get('font'),id,name));
function stack(font, family){return family?'"'+family+'", '+fonts[font][1]:fonts[font][1];}
function addSegment(text='새 문구',delay=0){if(get('segments').children.length>=12)return;const row=document.createElement('div');row.className='segment-row';
function field(name,label,type,value){const wrapper=document.createElement('label');wrapper.textContent=label;const input=document.createElement('input');input.type=type;input.dataset.field=name;input.value=value;if(type==='number'){input.min=0;input.max=30;input.step=.1;}if(type==='text')input.maxLength=80;wrapper.append(input);row.append(wrapper);return input;}
function select(name,label,options){const wrapper=document.createElement('label');wrapper.textContent=label;const s=document.createElement('select');s.dataset.field=name;options.forEach(([v,l])=>option(s,v,l));wrapper.append(s);row.append(wrapper);return s;}
field('text','문구','text',text);select('enter','등장',[['fade-in','페이드 등장'],['rise','아래에서 상승'],['zoom-in','확대 등장'],['flip-in','입체 회전'],['none','없음']]);select('glow','빛',[['none','없음'],['glow','빛남'],['pulse','빛 맥동'],['shine','빛 훑기']]);select('exit','사라짐',[['none','유지'],['fade-out','페이드 퇴장'],['sink','아래로 퇴장'],['zoom-out','축소 퇴장']]);const font=select('font','서체',Object.entries(fonts).map(([id,[name]])=>[id,name]));font.value='gothic';field('delay','시작(초)','number',delay);field('duration','등장(초)','number',1);field('hold','유지(초)','number',2);field('color','글자색','color','#eee3d4');field('glow_color','빛 색','color','#ad79ff');const remove=document.createElement('button');remove.textContent='삭제';remove.type='button';remove.addEventListener('click',()=>{if(get('segments').children.length>1){row.remove();render();}});row.append(remove);get('segments').append(row);}
addSegment('더',0);addSegment('아리랑',1);addSegment('스토어',2);
get('add-segment').addEventListener('click',()=>addSegment());
function render(){get('segment-editor').hidden=!get('individual').checked;get('error').textContent='';const family=get('font-family').value.trim();if(family&&!/^[\p{L}\p{N}_ -]{1,80}$/u.test(family)){get('error').textContent='폰트 이름에는 문자·숫자·공백·하이픈만 입력하세요.';return false;}
const e=effects.find(e=>e.id===get('effect').value),doc=new DOMParser().parseFromString(template,'text/html');doc.querySelector('.apf-gate').dataset.effect=e.id;const title=get('title').value.trim()||'ARKAON',subtitle=get('subtitle').value.trim()||'당신의 아이디어가 현실이 되는 순간';const h=doc.querySelector('.apf-title');h.textContent='';
if(get('individual').checked){h.classList.add('apf-custom-title');const layered=get('layered').checked;if(layered&&(e.id!=='arkaon-cinematic-gate'||get('segments').children.length!==3)){get('error').textContent='중앙 적층은 시네마틱 게이트에서 문구 3개일 때 사용하세요.';return false;}const group=doc.createElement('span');group.className=layered?'apf-layered':'apf-text-group';const labels=[];for(const row of get('segments').children){const value=k=>row.querySelector('[data-field="'+k+'"]').value,text=value('text').trim();if(!text){get('error').textContent='각 문구를 입력하세요.';return false;}const delay=Number(value('delay')),duration=Number(value('duration')),hold=Number(value('hold'));if([delay,duration,hold].some(x=>!Number.isFinite(x)||x<0||x>30)){get('error').textContent='시작·등장·유지 시간은 0–30초로 입력하세요.';return false;}
const segment=doc.createElement('span');segment.className='apf-text-segment';segment.setAttribute('aria-hidden','true');const css={'--apf-font':uploadedFont?'"APF Uploaded", '+fonts[value('font')][1]:stack(value('font'),family),'--apf-color':value('color'),'--apf-glow-color':value('glow_color'),'--apf-delay':delay+'s','--apf-in-duration':duration+'s','--apf-out-duration':'1s','--apf-exit-delay':(delay+duration+hold)+'s','--apf-enter-name':value('enter')==='none'?'apf-text-still':'apf-text-'+value('enter'),'--apf-exit-name':value('exit')==='none'?'apf-text-still':'apf-text-'+value('exit')};Object.entries(css).forEach(([k,v])=>segment.style.setProperty(k,v));const exit=doc.createElement('span');exit.className='apf-text-exit';const glow=doc.createElement('span');glow.className='apf-text-glow';glow.dataset.glow=value('glow');glow.textContent=text;exit.append(glow);segment.append(exit);if(layered){const word=doc.createElement('span');word.className='apf-word apf-word-'+['left','center','right'][labels.length];word.append(segment);group.append(word);}else group.append(segment);labels.push(text);}group.setAttribute('aria-label',labels.join(' '));h.append(group);
}else if(e.id==='arkaon-stagger-rise'){const wrapper=doc.createElement('span');wrapper.setAttribute('aria-label',title);const chars=typeof Intl.Segmenter==='function'?[...new Intl.Segmenter('ko',{granularity:'grapheme'}).segment(title)].map(x=>x.segment):Array.from(title);chars.forEach((char,i)=>{const span=doc.createElement('span');span.className='apf-char';span.setAttribute('aria-hidden','true');span.style.setProperty('--apf-progress',String(i/Math.max(1,chars.length-1)));span.textContent=char;wrapper.append(span);});h.append(wrapper);}else h.textContent=title;
doc.querySelector('.apf-subtitle').textContent=subtitle;const fontStyle=doc.createElement('style');fontStyle.textContent=(uploadedFont?'@font-face{font-family:"APF Uploaded";src:url('+uploadedFont+') format("woff2");font-display:swap}':'')+'.apf-title,.apf-subtitle{font-family:'+(uploadedFont?'"APF Uploaded", '+fonts[get('font').value][1]:stack(get('font').value,family))+'}';doc.head.append(fontStyle);doc.documentElement.style.setProperty('--apf-accent',get('accent').value);doc.documentElement.style.setProperty('--apf-background',get('background').value);doc.documentElement.style.setProperty('--apf-duration',get('duration').value+'s');output='<!doctype html>'+doc.documentElement.outerHTML;get('preview').srcdoc=output;get('description').textContent=e.description+' · 호출 이름: '+e.id;return true;}
get('play').addEventListener('click',render);['effect','accent','background','duration','font','individual','layered'].forEach(id=>get(id).addEventListener('change',render));
get('font-file').addEventListener('change',async()=>{uploadedFont='';const file=get('font-file').files[0];if(!file){render();return;}if(file.size>2*1024*1024){get('error').textContent='WOFF2 폰트는 2MB 이하로 선택하세요.';return;}try{const bytes=await file.arrayBuffer();if(new TextDecoder().decode(bytes.slice(0,4))!=='wOF2')throw Error('WOFF2 형식의 폰트를 선택하세요.');const reader=new FileReader();const data=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(new Blob([bytes],{type:'font/woff2'}));});const face=new FontFace('APF Uploaded','url('+data+')');await face.load();uploadedFont=data;render();}catch(error){get('error').textContent='폰트를 읽을 수 없습니다. 유효한 WOFF2 파일을 선택하세요.';}});
get('download').addEventListener('click',()=>{if(!render())return;const url=URL.createObjectURL(new Blob([output],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=get('effect').value+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});render();
